export const API = {
  LOGIN: "/auth/passwordlogin/",
  REGISTER: "/auth/registernewuser/",
  REGISTER_OTP: "/auth/registersendotp/",
  LOGIN_OTP: "/auth/loginotp/",
  VERIFY_LOGIN_OTP: "/auth/verifyloginotp/",
  RESET_PASSWORD: "/auth/resetpassword/",
  VERIFY_RESET_PASSWORD: "/auth/verifyresetpassword/",
  EMAIL_SEND_OTP: "/auth/emailsendotp/",
  VERIFY_EMAIL_OTP: "/auth/verifyemailotp/",
  MENTOR_PROFILE: "/mentor/profile",
  MENTOR_ALL_PROFILES: "/mentor/all",
  MENTOR_LIKE: "/mentor/likes",
  MENTOR_RATING: "/mentor/rating",
  STUDENT_PROFILE: "/student/profile",
  COMMON_QUALIFICATION: "/common/qualification",
  COMMON_DOCUMENT_NAME: "/common/documentname",
  COMMON_COURSES: "/common/courses",
};